// Seeded marketplace creators.
//
// Invented people. Names, headlines and bios are written for this rebuild and
// avatars are generated (DiceBear). Nothing here is scraped from naano.com — we
// are cloning the product, not republishing real creators' identities.
//
// Economics follow naano's published medians: EUR 84 under 5K followers,
// EUR 180 at 5-10K, EUR 312 at 10-25K, rising to EUR 400-1500 for top creators.

export type Creator = {
  id: string;
  slug: string;
  name: string;
  headline: string;
  avatar: string;
  country: string;
  countryCode: string;
  flag: string;
  verticals: string[];
  bio: string;
  followers: number;
  medianViews: number;
  postCost: number;
  matchScore: number;
  engagementRate: number;
  reactionsPerPost: number;
  commentsPerPost: number;
  icp: string[];
};

export const VERTICALS = ["Sales", "RevOps", "DevTools", "HR-Tech", "Product", "Marketing Ops", "Fintech", "Vertical SaaS"] as const;

export const CREATORS: Creator[] = [
  {"id": "cr_004", "slug": "tomas-haddad", "name": "Tomas Haddad", "headline": "Talent ops. Hiring that does not waste anybody's time", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=tomas-haddad&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Nigeria", "countryCode": "NG", "flag": "🇳🇬", "verticals": ["HR-Tech", "People Ops"], "bio": "Hiring and people ops for technical teams. I write about scorecards, comp bands and the interviews that should have been an email.", "followers": 24520, "medianViews": 13680, "postCost": 200, "matchScore": 98, "engagementRate": 3.0, "reactionsPerPost": 410, "commentsPerPost": 66, "icp": ["Talent partners", "People leads", "Founders"]},
  {"id": "cr_009", "slug": "ingrid-lindqvist", "name": "Ingrid Lindqvist", "headline": "Enterprise AE. I write about the deals that actually close", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=ingrid-lindqvist&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Germany", "countryCode": "DE", "flag": "🇩🇪", "verticals": ["Sales", "GTM"], "bio": "Fifteen years carrying a number, now writing about what actually moves pipeline. Long-form breakdowns of real deals, the ones that stalled included.", "followers": 2641, "medianViews": 2117, "postCost": 80, "matchScore": 95, "engagementRate": 2.6, "reactionsPerPost": 55, "commentsPerPost": 8, "icp": ["AEs", "Sales leaders", "Founders"]},
  {"id": "cr_014", "slug": "nadia-bianchi", "name": "Nadia Bianchi", "headline": "Lifecycle and marketing ops for B2B SaaS", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=nadia-bianchi&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Italy", "countryCode": "IT", "flag": "🇮🇹", "verticals": ["Marketing Ops", "Demand Gen"], "bio": "Demand gen and marketing ops. My posts are the spreadsheets my CFO makes me justify, rewritten so they are readable.", "followers": 2933, "medianViews": 4179, "postCost": 80, "matchScore": 95, "engagementRate": 2.82, "reactionsPerPost": 118, "commentsPerPost": 17, "icp": ["Demand gen leads", "CMOs", "Growth"]},
  {"id": "cr_005", "slug": "bruno-nyberg", "name": "Bruno Nyberg", "headline": "PM writing about the roadmap decisions nobody posts about", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=bruno-nyberg&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Italy", "countryCode": "IT", "flag": "🇮🇹", "verticals": ["Product", "PLG"], "bio": "Product manager in B2B SaaS. I publish the roadmap trade-offs and the features we killed, which is the more useful half.", "followers": 1569, "medianViews": 2117, "postCost": 100, "matchScore": 94, "engagementRate": 2.46, "reactionsPerPost": 52, "commentsPerPost": 9, "icp": ["PMs", "Heads of Product", "Designers"]},
  {"id": "cr_020", "slug": "amara-nyberg", "name": "Amara Nyberg", "headline": "People leader writing about the messy middle of scaling teams", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=amara-nyberg&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Nigeria", "countryCode": "NG", "flag": "🇳🇬", "verticals": ["HR-Tech", "People Ops"], "bio": "Hiring and people ops for technical teams. I write about scorecards, comp bands and the interviews that should have been an email.", "followers": 22642, "medianViews": 15374, "postCost": 420, "matchScore": 93, "engagementRate": 1.81, "reactionsPerPost": 279, "commentsPerPost": 37, "icp": ["Talent partners", "People leads", "Founders"]},
  {"id": "cr_021", "slug": "matteo-almeida", "name": "Matteo Almeida", "headline": "Discovery, delivery, and saying no", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=matteo-almeida&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Ireland", "countryCode": "IE", "flag": "🇮🇪", "verticals": ["Product", "Design"], "bio": "Product manager in B2B SaaS. I publish the roadmap trade-offs and the features we killed, which is the more useful half.", "followers": 10112, "medianViews": 5924, "postCost": 420, "matchScore": 92, "engagementRate": 3.36, "reactionsPerPost": 199, "commentsPerPost": 32, "icp": ["PMs", "Heads of Product", "Designers"]},
  {"id": "cr_024", "slug": "rafael-halvorsen", "name": "Rafael Halvorsen", "headline": "Ops-heavy SaaS and the customers who love it", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=rafael-halvorsen&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Italy", "countryCode": "IT", "flag": "🇮🇹", "verticals": ["Vertical SaaS", "Ops"], "bio": "Operator in vertical SaaS. I write about serving industries that never show up in a SaaS conference keynote.", "followers": 21551, "medianViews": 26163, "postCost": 320, "matchScore": 91, "engagementRate": 3.2, "reactionsPerPost": 837, "commentsPerPost": 184, "icp": ["Founders", "COOs", "Ops leads"]},
  {"id": "cr_026", "slug": "silke-raman", "name": "Silke Raman", "headline": "Revenue systems, attribution and the truth about your CRM", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=silke-raman&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Germany", "countryCode": "DE", "flag": "🇩🇪", "verticals": ["RevOps", "Analytics"], "bio": "I rebuild revenue reporting for scaleups. Posts are mostly about attribution, forecast hygiene and why your dashboard disagrees with your bank account.", "followers": 8343, "medianViews": 4862, "postCost": 160, "matchScore": 91, "engagementRate": 2.96, "reactionsPerPost": 144, "commentsPerPost": 26, "icp": ["RevOps leads", "CROs", "Sales ops"]},
  {"id": "cr_025", "slug": "ingrid-diallo", "name": "Ingrid Diallo", "headline": "Helping B2B teams book meetings without spray-and-pray", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=ingrid-diallo&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "France", "countryCode": "FR", "flag": "🇫🇷", "verticals": ["Sales", "Outbound"], "bio": "Fifteen years carrying a number, now writing about what actually moves pipeline. Long-form breakdowns of real deals, the ones that stalled included.", "followers": 1174, "medianViews": 788, "postCost": 100, "matchScore": 90, "engagementRate": 1.65, "reactionsPerPost": 13, "commentsPerPost": 2, "icp": ["AEs", "Sales leaders", "Founders"]},
  {"id": "cr_002", "slug": "tomas-el-amrani", "name": "Tomas El Amrani", "headline": "Revenue systems, attribution and the truth about your CRM", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=tomas-el-amrani&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Germany", "countryCode": "DE", "flag": "🇩🇪", "verticals": ["RevOps", "Analytics"], "bio": "I rebuild revenue reporting for scaleups. Posts are mostly about attribution, forecast hygiene and why your dashboard disagrees with your bank account.", "followers": 23106, "medianViews": 12904, "postCost": 260, "matchScore": 89, "engagementRate": 1.67, "reactionsPerPost": 215, "commentsPerPost": 23, "icp": ["RevOps leads", "CROs", "Sales ops"]},
  {"id": "cr_029", "slug": "hanna-lund", "name": "Hanna Lund", "headline": "Discovery, delivery, and saying no", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=hanna-lund&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "France", "countryCode": "FR", "flag": "🇫🇷", "verticals": ["Product", "PLG"], "bio": "Product manager in B2B SaaS. I publish the roadmap trade-offs and the features we killed, which is the more useful half.", "followers": 24699, "medianViews": 21115, "postCost": 380, "matchScore": 89, "engagementRate": 2.15, "reactionsPerPost": 454, "commentsPerPost": 59, "icp": ["PMs", "Heads of Product", "Designers"]},
  {"id": "cr_013", "slug": "aisha-mensah", "name": "Aisha Mensah", "headline": "Discovery, delivery, and saying no", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=aisha-mensah&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Singapore", "countryCode": "SG", "flag": "🇸🇬", "verticals": ["Product", "Design"], "bio": "Product manager in B2B SaaS. I publish the roadmap trade-offs and the features we killed, which is the more useful half.", "followers": 6757, "medianViews": 7464, "postCost": 120, "matchScore": 88, "engagementRate": 2.49, "reactionsPerPost": 186, "commentsPerPost": 17, "icp": ["PMs", "Heads of Product", "Designers"]},
  {"id": "cr_008", "slug": "amara-ferreira", "name": "Amara Ferreira", "headline": "Vertical SaaS operator. Niche beats broad", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=amara-ferreira&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "France", "countryCode": "FR", "flag": "🇫🇷", "verticals": ["Vertical SaaS", "SaaS"], "bio": "Operator in vertical SaaS. I write about serving industries that never show up in a SaaS conference keynote.", "followers": 2201, "medianViews": 1764, "postCost": 100, "matchScore": 87, "engagementRate": 3.06, "reactionsPerPost": 54, "commentsPerPost": 10, "icp": ["Founders", "COOs", "Ops leads"]},
  {"id": "cr_011", "slug": "lea-ferreira", "name": "Léa Ferreira", "headline": "Staff engineer writing about the tools we actually keep", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=lea-ferreira&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "France", "countryCode": "FR", "flag": "🇫🇷", "verticals": ["DevTools", "Open Source"], "bio": "Engineer first, writer second. I review developer tooling the way I evaluate it at work: does it survive a bad on-call week.", "followers": 8218, "medianViews": 10851, "postCost": 120, "matchScore": 87, "engagementRate": 1.47, "reactionsPerPost": 159, "commentsPerPost": 15, "icp": ["Backend engineers", "Platform teams", "CTOs"]},
  {"id": "cr_022", "slug": "ingrid-adeyemi", "name": "Ingrid Adeyemi", "headline": "Demand gen that survives a CFO review", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=ingrid-adeyemi&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Singapore", "countryCode": "SG", "flag": "🇸🇬", "verticals": ["Marketing Ops", "Demand Gen"], "bio": "Demand gen and marketing ops. My posts are the spreadsheets my CFO makes me justify, rewritten so they are readable.", "followers": 3663, "medianViews": 3328, "postCost": 120, "matchScore": 85, "engagementRate": 2.37, "reactionsPerPost": 79, "commentsPerPost": 12, "icp": ["Demand gen leads", "CMOs", "Growth"]},
  {"id": "cr_027", "slug": "hanna-nyberg", "name": "Hanna Nyberg", "headline": "I build in public and ship on Fridays anyway", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=hanna-nyberg&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Belgium", "countryCode": "BE", "flag": "🇧🇪", "verticals": ["DevTools", "Engineering"], "bio": "Engineer first, writer second. I review developer tooling the way I evaluate it at work: does it survive a bad on-call week.", "followers": 19939, "medianViews": 11718, "postCost": 420, "matchScore": 85, "engagementRate": 2.73, "reactionsPerPost": 320, "commentsPerPost": 54, "icp": ["Backend engineers", "Platform teams", "CTOs"]},
  {"id": "cr_030", "slug": "greta-duarte", "name": "Greta Duarte", "headline": "I measure the things that pay salaries", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=greta-duarte&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Germany", "countryCode": "DE", "flag": "🇩🇪", "verticals": ["Marketing Ops", "Demand Gen"], "bio": "Demand gen and marketing ops. My posts are the spreadsheets my CFO makes me justify, rewritten so they are readable.", "followers": 452749, "medianViews": 563246, "postCost": 1240, "matchScore": 85, "engagementRate": 1.41, "reactionsPerPost": 7942, "commentsPerPost": 1285, "icp": ["Demand gen leads", "CMOs", "Growth"]},
  {"id": "cr_003", "slug": "andrei-navarro", "name": "Andrei Navarro", "headline": "DX and developer tooling. Opinions from production", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=andrei-navarro&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Belgium", "countryCode": "BE", "flag": "🇧🇪", "verticals": ["DevTools", "Open Source"], "bio": "Engineer first, writer second. I review developer tooling the way I evaluate it at work: does it survive a bad on-call week.", "followers": 27950, "medianViews": 34695, "postCost": 920, "matchScore": 84, "engagementRate": 1.41, "reactionsPerPost": 490, "commentsPerPost": 75, "icp": ["Backend engineers", "Platform teams", "CTOs"]},
  {"id": "cr_031", "slug": "rafael-okafor", "name": "Rafael Okafor", "headline": "Payments infrastructure, explained without the jargon", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=rafael-okafor&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Spain", "countryCode": "ES", "flag": "🇪🇸", "verticals": ["Fintech", "Finance"], "bio": "Payments and B2B finance infrastructure. I explain the boring plumbing that decides whether your money arrives on time.", "followers": 4621, "medianViews": 4269, "postCost": 80, "matchScore": 84, "engagementRate": 1.31, "reactionsPerPost": 56, "commentsPerPost": 12, "icp": ["Finance leads", "CFOs", "Fintech PMs"]},
  {"id": "cr_019", "slug": "noor-ferreira", "name": "Noor Ferreira", "headline": "I build in public and ship on Fridays anyway", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=noor-ferreira&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "United States", "countryCode": "US", "flag": "🇺🇸", "verticals": ["DevTools", "Engineering"], "bio": "Engineer first, writer second. I review developer tooling the way I evaluate it at work: does it survive a bad on-call week.", "followers": 1492, "medianViews": 1400, "postCost": 80, "matchScore": 83, "engagementRate": 2.57, "reactionsPerPost": 36, "commentsPerPost": 4, "icp": ["Backend engineers", "Platform teams", "CTOs"]},
  {"id": "cr_007", "slug": "marta-rostami", "name": "Marta Rostami", "headline": "Fintech operator. Compliance is a feature", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=marta-rostami&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "France", "countryCode": "FR", "flag": "🇫🇷", "verticals": ["Fintech", "Payments"], "bio": "Payments and B2B finance infrastructure. I explain the boring plumbing that decides whether your money arrives on time.", "followers": 2617, "medianViews": 2153, "postCost": 100, "matchScore": 82, "engagementRate": 1.49, "reactionsPerPost": 32, "commentsPerPost": 5, "icp": ["Finance leads", "CFOs", "Fintech PMs"]},
  {"id": "cr_016", "slug": "lea-okafor", "name": "Léa Okafor", "headline": "Building software for industries nobody demos on stage", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=lea-okafor&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Belgium", "countryCode": "BE", "flag": "🇧🇪", "verticals": ["Vertical SaaS", "Ops"], "bio": "Operator in vertical SaaS. I write about serving industries that never show up in a SaaS conference keynote.", "followers": 99045, "medianViews": 149462, "postCost": 1320, "matchScore": 82, "engagementRate": 2.63, "reactionsPerPost": 3935, "commentsPerPost": 441, "icp": ["Founders", "COOs", "Ops leads"]},
  {"id": "cr_018", "slug": "bruno-fonseca", "name": "Bruno Fonseca", "headline": "I fix broken funnels for a living", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=bruno-fonseca&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "United Kingdom", "countryCode": "GB", "flag": "🇬🇧", "verticals": ["RevOps", "GTM"], "bio": "I rebuild revenue reporting for scaleups. Posts are mostly about attribution, forecast hygiene and why your dashboard disagrees with your bank account.", "followers": 3285, "medianViews": 5234, "postCost": 60, "matchScore": 79, "engagementRate": 1.99, "reactionsPerPost": 104, "commentsPerPost": 16, "icp": ["RevOps leads", "CROs", "Sales ops"]},
  {"id": "cr_028", "slug": "mikkel-rossi", "name": "Mikkel Rossi", "headline": "Recruiting for engineering teams, minus the theatre", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=mikkel-rossi&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Spain", "countryCode": "ES", "flag": "🇪🇸", "verticals": ["HR-Tech", "Hiring"], "bio": "Hiring and people ops for technical teams. I write about scorecards, comp bands and the interviews that should have been an email.", "followers": 5583, "medianViews": 8350, "postCost": 200, "matchScore": 79, "engagementRate": 1.43, "reactionsPerPost": 119, "commentsPerPost": 22, "icp": ["Talent partners", "People leads", "Founders"]},
  {"id": "cr_023", "slug": "freya-raman", "name": "Freya Raman", "headline": "B2B finance stacks and the cost of getting them wrong", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=freya-raman&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Sweden", "countryCode": "SE", "flag": "🇸🇪", "verticals": ["Fintech", "Payments"], "bio": "Payments and B2B finance infrastructure. I explain the boring plumbing that decides whether your money arrives on time.", "followers": 2552, "medianViews": 3541, "postCost": 80, "matchScore": 78, "engagementRate": 1.38, "reactionsPerPost": 49, "commentsPerPost": 4, "icp": ["Finance leads", "CFOs", "Fintech PMs"]},
  {"id": "cr_032", "slug": "isabelle-moreau", "name": "Isabelle Moreau", "headline": "Ops-heavy SaaS and the customers who love it", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=isabelle-moreau&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "United Kingdom", "countryCode": "GB", "flag": "🇬🇧", "verticals": ["Vertical SaaS", "Ops"], "bio": "Operator in vertical SaaS. I write about serving industries that never show up in a SaaS conference keynote.", "followers": 4174, "medianViews": 5731, "postCost": 120, "matchScore": 78, "engagementRate": 2.74, "reactionsPerPost": 157, "commentsPerPost": 33, "icp": ["Founders", "COOs", "Ops leads"]},
  {"id": "cr_010", "slug": "beatriz-tanaka", "name": "Beatriz Tanaka", "headline": "I fix broken funnels for a living", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=beatriz-tanaka&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Belgium", "countryCode": "BE", "flag": "🇧🇪", "verticals": ["RevOps", "GTM"], "bio": "I rebuild revenue reporting for scaleups. Posts are mostly about attribution, forecast hygiene and why your dashboard disagrees with your bank account.", "followers": 9737, "medianViews": 5481, "postCost": 260, "matchScore": 77, "engagementRate": 2.97, "reactionsPerPost": 163, "commentsPerPost": 20, "icp": ["RevOps leads", "CROs", "Sales ops"]},
  {"id": "cr_012", "slug": "noor-haddad", "name": "Noor Haddad", "headline": "Recruiting for engineering teams, minus the theatre", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=noor-haddad&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "France", "countryCode": "FR", "flag": "🇫🇷", "verticals": ["HR-Tech", "People Ops"], "bio": "Hiring and people ops for technical teams. I write about scorecards, comp bands and the interviews that should have been an email.", "followers": 7108, "medianViews": 10563, "postCost": 200, "matchScore": 77, "engagementRate": 1.28, "reactionsPerPost": 135, "commentsPerPost": 17, "icp": ["Talent partners", "People leads", "Founders"]},
  {"id": "cr_006", "slug": "isabelle-adeyemi", "name": "Isabelle Adeyemi", "headline": "I measure the things that pay salaries", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=isabelle-adeyemi&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Belgium", "countryCode": "BE", "flag": "🇧🇪", "verticals": ["Marketing Ops", "Lifecycle"], "bio": "Demand gen and marketing ops. My posts are the spreadsheets my CFO makes me justify, rewritten so they are readable.", "followers": 1605, "medianViews": 2147, "postCost": 100, "matchScore": 76, "engagementRate": 2.1, "reactionsPerPost": 45, "commentsPerPost": 5, "icp": ["Demand gen leads", "CMOs", "Growth"]},
  {"id": "cr_015", "slug": "theo-vasseur", "name": "Theo Vasseur", "headline": "Fintech operator. Compliance is a feature", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=theo-vasseur&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Netherlands", "countryCode": "NL", "flag": "🇳🇱", "verticals": ["Fintech", "Finance"], "bio": "Payments and B2B finance infrastructure. I explain the boring plumbing that decides whether your money arrives on time.", "followers": 22231, "medianViews": 31232, "postCost": 280, "matchScore": 74, "engagementRate": 3.27, "reactionsPerPost": 1020, "commentsPerPost": 120, "icp": ["Finance leads", "CFOs", "Fintech PMs"]},
  {"id": "cr_017", "slug": "andrei-bianchi", "name": "Andrei Bianchi", "headline": "Enterprise AE. I write about the deals that actually close", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=andrei-bianchi&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "France", "countryCode": "FR", "flag": "🇫🇷", "verticals": ["Sales", "GTM"], "bio": "Fifteen years carrying a number, now writing about what actually moves pipeline. Long-form breakdowns of real deals, the ones that stalled included.", "followers": 2315, "medianViews": 3658, "postCost": 60, "matchScore": 73, "engagementRate": 3.42, "reactionsPerPost": 125, "commentsPerPost": 21, "icp": ["AEs", "Sales leaders", "Founders"]},
  {"id": "cr_001", "slug": "beatriz-diallo", "name": "Beatriz Diallo", "headline": "Helping B2B teams book meetings without spray-and-pray", "avatar": "https://api.dicebear.com/9.x/notionists/svg?seed=beatriz-diallo&backgroundColor=e8f0fe,dceaff,f3f4f6", "country": "Brazil", "countryCode": "BR", "flag": "🇧🇷", "verticals": ["Sales", "Outbound"], "bio": "Fifteen years carrying a number, now writing about what actually moves pipeline. Long-form breakdowns of real deals, the ones that stalled included.", "followers": 23749, "medianViews": 23000, "postCost": 400, "matchScore": 72, "engagementRate": 2.13, "reactionsPerPost": 490, "commentsPerPost": 79, "icp": ["AEs", "Sales leaders", "Founders"]}
];

export const followerTier = (f: number) =>
  f < 5000 ? "1K-5K" : f < 10000 ? "5K-10K" : f < 25000 ? "10K-25K" : f < 75000 ? "25K-75K" : "75K+";

export const TIERS = ["1K-5K", "5K-10K", "10K-25K", "25K-75K", "75K+"] as const;

export const COUNTRIES = Array.from(
  new Map(CREATORS.map((c) => [c.countryCode, { code: c.countryCode, name: c.country, flag: c.flag }])).values()
).sort((a, b) => a.name.localeCompare(b.name));

export const getCreator = (slug: string) => CREATORS.find((c) => c.slug === slug);
