import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "./globals.css";

const display = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
  display: "swap",
});

const sans = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const DESCRIPTION =
  "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.";

export const metadata: Metadata = {
  // Tracked links get pasted into LinkedIn; without these the unfurl is blank,
  // which for a product about link attribution is a bad first impression.
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"
  ),
  title: {
    default: "Naano — The B2B LinkedIn Creator Marketplace",
    template: "%s · Naano",
  },
  description: DESCRIPTION,
  openGraph: {
    title: "Naano — The B2B LinkedIn Creator Marketplace",
    description: DESCRIPTION,
    type: "website",
    siteName: "Naano",
  },
  twitter: { card: "summary_large_image", description: DESCRIPTION },
  robots: { index: false, follow: false },
};

export const viewport = {
  themeColor: "#1652f0",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${display.variable} ${sans.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
