import Link from "next/link";
import { Nav } from "@/components/site/Nav";
import { Footer } from "@/components/site/Footer";
import { ScaleFrame } from "@/components/site/ScaleFrame";
import { Testimonial } from "@/components/site/Testimonial";
import { MarketplaceShowcase } from "@/components/site/MarketplaceShowcase";
import { CampaignJourney } from "@/components/site/CampaignJourney";
import { ProofSection } from "@/components/site/ProofSection";
import { ResultsSection } from "@/components/site/ResultsSection";
import { PricingSection } from "@/components/site/PricingSection";
import { FaqSection } from "@/components/site/FaqSection";
import { BookSection } from "@/components/site/BookSection";

export default function Home() {
  return (
    <>
      <ScaleFrame>
        <Nav />

        {/* ---------------------------------------------------------------- hero */}
        {/* naano's hero is a centred flex column filling the viewport below the
            bar — min-height calc(100vh - 74), padding 40/84/60 — not a block
            with a fixed top padding. The rhythm between the pieces is theirs:
            40 / 30 / 44 / 34 / 48. They have no stats bar, so neither do we. */}
        <section data-nav-hero className="nn-sky pt-[73px]">
          <div className="flex w-full flex-col items-center justify-center px-5 pb-[60px] pt-10 text-center lg:min-h-[calc(100vh-73px)] lg:px-[84px]">
            <span className="inline-flex items-center gap-2.5 rounded-full bg-white/[0.92] pb-[9px] pl-[14px] pr-[18px] pt-[9px] text-[16px] font-normal leading-[21px] text-[#17181c] shadow-[0_1px_3px_rgba(15,23,42,0.06)]">
              <svg
                viewBox="0 0 24 24"
                className="size-[15px]"
                aria-hidden
                fill="currentColor"
              >
                <path d="M18.9 2H22l-7 8 8.2 12h-6.4l-5-7.3L5.9 22H2.8l7.5-8.6L2.4 2h6.6l4.5 6.7L18.9 2z" />
              </svg>
              <span className="grid size-[17px] place-items-center rounded-[3px] bg-[#0a66c2] text-[10px] font-bold leading-none text-white">
                in
              </span>
              Where B2B brands work with creators
            </span>

            <h1 className="mx-auto mt-[40px] max-w-[1000px] font-sans text-[clamp(2.6rem,5.35vw,77px)] font-semibold leading-[1.05] tracking-[-0.04em] text-[#17181c]">
              The B2B LinkedIn
              <br className="hidden sm:block" />
              {" Creator Marketplace."}
            </h1>

            <p className="mx-auto mt-[30px] max-w-[660px] text-[21px] leading-[31.5px] text-[#43454c]">
              Find the creators your buyers already trust, launch campaigns in
              days, and track the clicks, leads and pipeline generated by every
              post.
            </p>

            <div className="mt-[44px] flex flex-wrap items-center justify-center gap-x-6 gap-y-3">
              <Link
                href="/register?role=saas"
                className="inline-flex items-center gap-[11px] rounded-xl bg-[#17181c] px-7 py-4 text-[16px] font-semibold leading-5 text-white transition hover:opacity-90"
              >
                Launch a campaign{" "}
                <svg
                  viewBox="0 0 24 24"
                  className="size-[15px]"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2.2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden
                >
                  <path d="M5 12h13M13 6l6 6-6 6" />
                </svg>
              </Link>
              <Link
                href="/#how-it-works"
                className="inline-flex items-center gap-[11px] text-[16px] font-semibold leading-none text-[#17181c] transition hover:opacity-70"
              >
                See how Naano works{" "}
                <svg
                  viewBox="0 0 24 24"
                  className="size-[15px]"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2.2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden
                >
                  <path d="M5 12h13M13 6l6 6-6 6" />
                </svg>
              </Link>
            </div>

            <p className="mt-[34px] inline-flex items-center gap-[11px] text-[16px] font-normal leading-5 text-[#43454c]">
              <svg
                viewBox="0 0 24 24"
                className="size-4"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.7"
                aria-hidden
              >
                <path d="M12 3l7 3v6c0 4.2-2.9 7.6-7 9-4.1-1.4-7-4.8-7-9V6l7-3z" />
                <path d="M9 12l2 2 4-4" />
              </svg>
              Trusted by modern B2B teams
            </p>

            {/* Trust marquee. Per-logo heights taken from naano's rendered sizes
              (their CSS box is taller — object-fit: contain fits inside it), so
              wordmarks do not tower over icon-led marks. The row renders twice
              and the track animates 0 -> -50% for a seamless 26s loop. */}
            <div className="nn-marquee-viewport mt-[48px] w-full">
              <div className="nn-marquee-track">
                {[0, 1].map((copy) => (
                  <div
                    key={copy}
                    className="flex shrink-0 items-center"
                    aria-hidden={copy === 1}
                  >
                    {[
                      { file: "lemlist", alt: "lemlist", h: 36 },
                      { file: "folk", alt: "folk.", h: 26 },
                      { file: "leadbay", alt: "LEADBAY", h: 24 },
                      { file: "ringover", alt: "ringover", h: 36 },
                      { file: "attio", alt: "attio", h: 36, multiply: true },
                      {
                        file: "lagrowthmachine",
                        alt: "La Growth Machine",
                        h: 29,
                      },
                      { file: "gojiberry", alt: "gojiberry", h: 28 },
                      { file: "chatseo", alt: "ChatSEO", h: 34 },
                      {
                        file: "abyssale",
                        alt: "Abyssale",
                        h: 26,
                        multiply: true,
                      },
                    ].map(({ file, alt, h, multiply }) => (
                      /* eslint-disable-next-line @next/next/no-img-element */
                      <img
                        key={`${copy}-${file}`}
                        src={`/lp/logo-${file}.png`}
                        alt={copy === 0 ? alt : ""}
                        style={{ height: `${h}px` }}
                        className={`nn-marquee-logo mx-[47px] ${multiply ? "mix-blend-multiply" : ""}`}
                      />
                    ))}

                    {/* BlogSEO rides in a white pill with a CASE STUDY link, as on naano */}
                    <Link
                      href="/#proof"
                      tabIndex={copy === 1 ? -1 : undefined}
                      className="mx-[47px] inline-flex shrink-0 items-center gap-3 rounded-full bg-white/[0.92] py-2 pl-[18px] pr-[9px] shadow-[0_1px_3px_rgba(15,23,42,0.06)]"
                    >
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src="/lp/logo-blogseo.png"
                        alt={copy === 0 ? "BlogSEO" : ""}
                        style={{ height: "16px" }}
                        className="w-auto object-contain"
                      />
                      <span className="inline-flex items-center gap-1.5 rounded-full bg-[#f2f1ee] px-2.5 py-1 text-[11px] font-bold uppercase tracking-[0.08em] text-[#17181c]">
                        Case study <span aria-hidden>→</span>
                      </span>
                    </Link>
                  </div>
                ))}
              </div>
            </div>

          </div>
        </section>

        <Testimonial />

        <MarketplaceShowcase />

        <CampaignJourney />
      </ScaleFrame>

      {/* naano's zoom frame stops here. From the proof section down their
          wrapper carries zoom 1 and the layout is plain responsive — checked
          at 1440, where .lp-system-testimonials and everything after it render
          unscaled while the hero block above is at 0.861244. Keeping these
          inside the frame made the whole lower half of the page render 14%
          small on any screen that is not exactly 1672 wide. */}
      <ProofSection />

      <ResultsSection />

      <PricingSection />

      <FaqSection />

      <BookSection />

      <Footer />
    </>
  );
}
