import Link from "next/link";
import { Nav } from "@/components/site/Nav";
import { Footer } from "@/components/site/Footer";
import { CreatorCard } from "@/components/CreatorCard";
import { CREATORS } from "@/lib/creators";
import { ScaleFrame } from "@/components/site/ScaleFrame";
import { Testimonial } from "@/components/site/Testimonial";
import { getCurrentUser } from "@/lib/session";

const FAQS = [
  [
    "How much does a post cost?",
    "Creators set their own flat fee per post, starting at €20. The median is €84 under 5K followers, €180 between 5K and 10K, and €312 between 10K and 25K. Top creators charge €400 to €1,500.",
  ],
  [
    "How is this different from LinkedIn Ads?",
    "You are borrowing trust, not buying impressions. In Q1 2026 our campaigns averaged €18 per lead against €55–90 on LinkedIn Ads, at a 12% click-through rate against a 0.8% benchmark.",
  ],
  [
    "How do you track results?",
    "Every post carries a unique tracked link. When somebody clicks it we record the click against that specific creator and campaign, then follow it through to leads and pipeline.",
  ],
  [
    "Are creators vetted?",
    "Yes. Around 2,000–3,000 creators across 100 countries, from roughly 1K to 500K followers, all working in B2B verticals: sales, RevOps, devtools, HR-tech, product, marketing ops, fintech and vertical SaaS.",
  ],
  [
    "What do I pay Naano?",
    "Self-Serve is €0 per month — you pay only for the posts you book. Managed is €700 per month and we run the campaigns for you.",
  ],
];

export default async function Home() {
  const featured = CREATORS.slice(0, 3);
  const user = await getCurrentUser();

  return (
    <ScaleFrame>
      <Nav />

      {/* ---------------------------------------------------------------- hero */}
      {/* Vertical rhythm measured off naano at 1440: 148px from the bar to the
          pill, then 34 / 26 / 38 / 29 / 41 between the blocks. naano has no
          stats bar in the hero, so there is none here either. */}
      <section className="nn-sky -mt-[73px] pt-[73px]">
        <div className="w-full px-[56px] pb-16 pt-[148px] text-center">
          <span className="inline-flex items-center gap-2 rounded-full bg-white/[0.92] pb-[9px] pl-[14px] pr-[18px] pt-[9px] text-[16px] font-normal leading-none text-[#17181c] shadow-[0_1px_3px_rgba(15,23,42,0.06)]">
            <svg viewBox="0 0 24 24" className="size-[15px]" aria-hidden fill="currentColor">
              <path d="M18.9 2H22l-7 8 8.2 12h-6.4l-5-7.3L5.9 22H2.8l7.5-8.6L2.4 2h6.6l4.5 6.7L18.9 2z" />
            </svg>
            <span className="grid size-[17px] place-items-center rounded-[3px] bg-[#0a66c2] text-[10px] font-bold leading-none text-white">
              in
            </span>
            Where B2B brands work with creators
          </span>

          <h1 className="mx-auto mt-[40px] max-w-[1000px] font-sans text-[clamp(2.6rem,5.35vw,77px)] font-semibold leading-[1.05] tracking-[-0.04em] text-[#17181c]">
            The B2B LinkedIn
            <br className="hidden sm:block" />
            {" Creator Marketplace."}
          </h1>

          <p className="mx-auto mt-[30px] max-w-[660px] text-[21px] leading-[31.5px] text-[#43454c]">
            Find the creators your buyers already trust, launch campaigns in days,
            and track the clicks, leads and pipeline generated by every post.
          </p>

          <div className="mt-[44px] flex flex-wrap items-center justify-center gap-x-9 gap-y-3">
            <Link
              href="/register?role=saas"
              className="inline-flex items-center gap-[11px] rounded-xl bg-[#17181c] px-7 py-[16px] text-[16px] font-semibold leading-none text-white transition hover:opacity-90"
            >
              Launch a campaign <svg viewBox="0 0 24 24" className="size-[15px]" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M5 12h13M13 6l6 6-6 6" /></svg>
            </Link>
            <Link
              href="/#how"
              className="inline-flex items-center gap-[11px] text-[16px] font-semibold leading-none text-[#17181c] transition hover:opacity-70"
            >
              See how Naano works <svg viewBox="0 0 24 24" className="size-[15px]" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M5 12h13M13 6l6 6-6 6" /></svg>
            </Link>
          </div>

          <p className="mt-[34px] inline-flex items-center gap-2 text-[15px] font-medium text-[#43454c]">
            <svg viewBox="0 0 24 24" className="size-4" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden>
              <path d="M12 3l7 3v6c0 4.2-2.9 7.6-7 9-4.1-1.4-7-4.8-7-9V6l7-3z" />
              <path d="M9 12l2 2 4-4" />
            </svg>
            Trusted by modern B2B teams
          </p>

          {/* Trust marquee. Per-logo heights taken from naano's rendered sizes
              (their CSS box is taller — object-fit: contain fits inside it), so
              wordmarks do not tower over icon-led marks. The row renders twice
              and the track animates 0 -> -50% for a seamless 26s loop. */}
          <div className="nn-marquee-viewport mt-[48px] w-full">
            <div className="nn-marquee-track">
              {[0, 1].map((copy) => (
                <div key={copy} className="flex shrink-0 items-center" aria-hidden={copy === 1}>
                  {[
                    { file: "lemlist", alt: "lemlist", h: 36 },
                    { file: "folk", alt: "folk.", h: 26 },
                    { file: "leadbay", alt: "LEADBAY", h: 24 },
                    { file: "ringover", alt: "ringover", h: 36 },
                    { file: "attio", alt: "attio", h: 36, multiply: true },
                    { file: "lagrowthmachine", alt: "La Growth Machine", h: 29 },
                    { file: "gojiberry", alt: "gojiberry", h: 28 },
                    { file: "chatseo", alt: "ChatSEO", h: 34 },
                    { file: "abyssale", alt: "Abyssale", h: 26, multiply: true },
                  ].map(({ file, alt, h, multiply }) => (
                    /* eslint-disable-next-line @next/next/no-img-element */
                    <img
                      key={`${copy}-${file}`}
                      src={`/lp/logo-${file}.png`}
                      alt={copy === 0 ? alt : ""}
                      style={{ height: `${h}px` }}
                      className={`nn-marquee-logo mx-[47px] ${multiply ? "mix-blend-multiply" : ""}`}
                    />
                  ))}

                  {/* BlogSEO rides in a white pill with a CASE STUDY link, as on naano */}
                  <Link
                    href="/#proof"
                    tabIndex={copy === 1 ? -1 : undefined}
                    className="mx-[47px] inline-flex shrink-0 items-center gap-3 rounded-full bg-white/[0.92] py-2 pl-[18px] pr-[9px] shadow-[0_1px_3px_rgba(15,23,42,0.06)]"
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src="/lp/logo-blogseo.png"
                      alt={copy === 0 ? "BlogSEO" : ""}
                      style={{ height: "16px" }}
                      className="w-auto object-contain"
                    />
                    <span className="inline-flex items-center gap-1.5 rounded-full bg-[#f2f1ee] px-2.5 py-1 text-[11px] font-bold uppercase tracking-[0.08em] text-[#17181c]">
                      Case study <span aria-hidden>→</span>
                    </span>
                  </Link>
                </div>
              ))}
            </div>
          </div>

          {/* scroll affordance, as naano has */}
          <div className="mt-12 flex justify-center">
            <a
              href="#how"
              aria-label="Scroll to how it works"
              className="grid size-9 place-items-center rounded-full bg-white/85 text-[#43454c] shadow-[0_1px_3px_rgba(15,23,42,0.08)] transition hover:bg-white"
            >
              <svg viewBox="0 0 24 24" className="size-4" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden>
                <path d="M6 9l6 6 6-6" />
              </svg>
            </a>
          </div>
        </div>
      </section>

      <Testimonial />

      {/* ------------------------------------------------------------ marketplace */}
      <section className="nn-sky border-y border-line">
        <div className="mx-auto max-w-6xl px-5 py-24">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div>
              <div className="nn-eyebrow">The marketplace</div>
              <h2 className="mt-3 font-sans text-4xl font-semibold tracking-[-0.03em] text-ink">
                Fit first, followers second
              </h2>
              <p className="mt-4 max-w-lg text-muted">
                Every creator is scored against your ICP before you ever see a
                follower count. Filter by vertical, audience size, price and country.
              </p>
            </div>
            <Link
              href="/marketplace"
              className="rounded-full bg-brand px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-brand-strong"
            >
              Browse all creators
            </Link>
          </div>

          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {featured.map((c, i) => (
              <CreatorCard key={c.id} creator={c} rank={i + 1} />
            ))}
          </div>
        </div>
      </section>

      {/* ----------------------------------------------------------------- proof */}
      <section className="mx-auto max-w-6xl px-5 py-24">
        <div className="text-center">
          <div className="nn-eyebrow">Q1 2026, first-party data</div>
          <h2 className="mt-3 font-sans text-4xl font-semibold tracking-[-0.03em] text-ink">
            Cheaper leads, by a distance
          </h2>
        </div>
        <div className="mt-12 grid gap-6 md:grid-cols-3">
          {[
            ["€18", "average cost per lead", "vs €55–90 on LinkedIn Ads"],
            ["12%", "click-through rate", "vs a 0.8% platform benchmark"],
            ["312", "campaigns run", "across eight B2B verticals"],
          ].map(([v, l, s]) => (
            <div key={l} className="nn-card p-8">
              <div className="font-display text-5xl font-extrabold text-brand">{v}</div>
              <div className="mt-3 font-display font-bold text-ink">{l}</div>
              <div className="mt-1 text-sm text-muted">{s}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ------------------------------------------------------------ case study */}
      <section className="mx-auto max-w-6xl px-5 pb-24">
        <div className="nn-card overflow-hidden">
          <div className="grid md:grid-cols-2">
            <div className="p-10">
              <div className="nn-eyebrow">Case study</div>
              <h3 className="mt-3 font-sans text-3xl font-semibold tracking-[-0.03em] text-ink">
                BlogSEO
              </h3>
              <p className="mt-4 leading-relaxed text-muted">
                Nine creators activated across SEO, content and growth. Every post
                carried its own tracked link, so each trial could be attributed to the
                creator who drove it.
              </p>
              <blockquote className="mt-8 border-l-2 border-brand pl-5">
                <p className="text-sm italic leading-relaxed text-ink">
                  “We manage €10M+ of influence budget every year. For B2B, Naano
                  simply makes our life easier.”
                </p>
                <footer className="mt-3 text-xs font-semibold text-muted">
                  David Zmirov · CEO, Zmirov Communication
                </footer>
              </blockquote>
            </div>
            <div className="grid grid-cols-1 gap-px bg-line sm:grid-cols-3 md:grid-cols-1">
              {[
                ["9", "creators activated"],
                ["2,940", "qualified clicks"],
                ["512", "trials started"],
              ].map(([v, l]) => (
                <div
                  key={l}
                  className="flex flex-col justify-center bg-[#f7faff] px-10 py-8"
                >
                  <div className="font-display text-4xl font-extrabold text-brand">{v}</div>
                  <div className="mt-1 text-sm font-medium text-muted">{l}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* --------------------------------------------------------------- pricing */}
      <section id="pricing" className="nn-sky scroll-mt-20 border-y border-line">
        <div className="mx-auto max-w-5xl px-5 py-24">
          <div className="text-center">
            <div className="nn-eyebrow">Pricing</div>
            <h2 className="mt-3 font-sans text-4xl font-semibold tracking-[-0.03em] text-ink">
              Pay per post, or hand it over
            </h2>
          </div>
          <div className="mt-14 grid gap-6 md:grid-cols-2">
            <div className="nn-card flex flex-col p-9">
              <h3 className="font-display text-lg font-bold text-ink">Self-Serve</h3>
              <div className="mt-4 font-display text-5xl font-extrabold text-ink">
                €0<span className="text-lg font-bold text-grey">/mo</span>
              </div>
              <p className="mt-3 text-sm text-muted">
                Browse, book and track yourself. You pay only for the posts you book.
              </p>
              <ul className="mt-7 space-y-3 text-sm text-ink">
                {[
                  "Full marketplace access",
                  "AI-drafted campaign briefs",
                  "Tracked links and attribution",
                  "Contracts, invoices and payouts",
                ].map((f) => (
                  <li key={f} className="flex gap-2.5">
                    <span className="text-success">✓</span>
                    {f}
                  </li>
                ))}
              </ul>
              <Link
                href="/register?role=saas"
                className="mt-auto pt-8 text-center"
              >
                <span className="block rounded-full border border-line bg-white px-5 py-3 text-sm font-semibold text-ink transition hover:border-grey">
                  Start free
                </span>
              </Link>
            </div>

            <div className="nn-card relative flex flex-col border-brand/30 p-9 ring-1 ring-brand/20">
              <span className="absolute -top-3 left-9 rounded-full bg-brand px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-white">
                Done for you
              </span>
              <h3 className="font-display text-lg font-bold text-ink">Managed</h3>
              <div className="mt-4 font-display text-5xl font-extrabold text-ink">
                €700<span className="text-lg font-bold text-grey">/mo</span>
              </div>
              <p className="mt-3 text-sm text-muted">
                We select the creators, write the briefs and run the campaigns.
              </p>
              <ul className="mt-7 space-y-3 text-sm text-ink">
                {[
                  "Everything in Self-Serve",
                  "Creator selection and outreach",
                  "Brief writing and review",
                  "Monthly performance reporting",
                ].map((f) => (
                  <li key={f} className="flex gap-2.5">
                    <span className="text-success">✓</span>
                    {f}
                  </li>
                ))}
              </ul>
              <Link href="/register?role=saas" className="mt-auto pt-8 text-center">
                <span className="block rounded-full bg-brand px-5 py-3 text-sm font-semibold text-white transition hover:bg-brand-strong">
                  Talk to us
                </span>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ------------------------------------------------------------------- faq */}
      <section className="mx-auto max-w-3xl px-5 py-24">
        <h2 className="text-center font-sans text-4xl font-semibold tracking-[-0.03em] text-ink">
          Questions
        </h2>
        <div className="mt-12 divide-y divide-line">
          {FAQS.map(([q, a]) => (
            <details key={q} className="group py-5">
              <summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-display font-bold text-ink marker:hidden">
                {q}
                <span className="text-xl text-grey transition group-open:rotate-45">
                  +
                </span>
              </summary>
              <p className="mt-3 text-sm leading-relaxed text-muted">{a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* ------------------------------------------------------------------- cta */}
      <section className="mx-auto max-w-6xl px-5 pb-24">
        <div className="overflow-hidden rounded-3xl bg-[linear-gradient(120deg,#1240d0,#1652f0_55%,#3080ff)] px-10 py-16 text-center">
          <h2 className="font-sans text-4xl font-semibold tracking-[-0.03em] text-white">
            Launch your first campaign this week
          </h2>
          <p className="mx-auto mt-4 max-w-lg text-white/80">
            Browse the marketplace free. Pay only when you book a post.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <Link
              href="/register?role=saas"
              className="rounded-full bg-white px-6 py-3 text-sm font-semibold text-brand transition hover:bg-brand-soft"
            >
              Find creators
            </Link>
            <Link
              href={user ? (user.role === "creator" ? "/studio" : "/app") : "/login"}
              className="rounded-full border border-white/40 px-6 py-3 text-sm font-semibold text-white transition hover:bg-white/10"
            >
              {user ? "Go to your dashboard" : "Sign in to a demo account"}
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </ScaleFrame>
  );
}
